twitter-to-kafka-service:
  twitter-keywords:
    - Java
    - MicroService
    - Elastic Search
    - Kafka
    - Spring
  welcome-message: My FirstSprigBootApp
  enable-v2-tweets: true
  enable-mock-tweets: false
  twitter-ve-base-url: https://api.twitter.com/2/tweets/search/stream?tweet.field=created_at&expansions=author_id
  twitter-v2-rules-base-url: https://api.twitter.com/2/tweets/search/stream/rules
  twitter-v2-bearer-token: ${TWITTER_BEARER_TOKEN}



